//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.0
//     from Assets/InputsSystem/GeneralGame.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputsSystem/GeneralGame.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @GeneralGame: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @GeneralGame()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GeneralGame"",
    ""maps"": [
        {
            ""name"": ""GeneralActions"",
            ""id"": ""3f955539-649a-4e93-8c88-06204128c60d"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""399e5fdc-818c-4582-9b30-9a937b69153d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeTime"",
                    ""type"": ""Button"",
                    ""id"": ""6909d46d-b7c0-4e6f-a46a-309bacd70248"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""456ca76a-acab-4c56-b8a8-5a1787e5a6a9"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a1ab800-2dde-4054-8ec8-73ead1b81520"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeTime"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UIIngame"",
            ""id"": ""6f37205e-061c-4179-8289-73d59101d83f"",
            ""actions"": [
                {
                    ""name"": ""OpenUIIngame"",
                    ""type"": ""Button"",
                    ""id"": ""df2eb058-90fb-4829-b9c6-e70663bc27ee"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5a1c7238-fd62-45de-bf4d-930d7062020e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenUIIngame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GeneralActions
        m_GeneralActions = asset.FindActionMap("GeneralActions", throwIfNotFound: true);
        m_GeneralActions_Newaction = m_GeneralActions.FindAction("New action", throwIfNotFound: true);
        m_GeneralActions_ChangeTime = m_GeneralActions.FindAction("ChangeTime", throwIfNotFound: true);
        // UIIngame
        m_UIIngame = asset.FindActionMap("UIIngame", throwIfNotFound: true);
        m_UIIngame_OpenUIIngame = m_UIIngame.FindAction("OpenUIIngame", throwIfNotFound: true);
    }

    ~@GeneralGame()
    {
        UnityEngine.Debug.Assert(!m_GeneralActions.enabled, "This will cause a leak and performance issues, GeneralGame.GeneralActions.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UIIngame.enabled, "This will cause a leak and performance issues, GeneralGame.UIIngame.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GeneralActions
    private readonly InputActionMap m_GeneralActions;
    private List<IGeneralActionsActions> m_GeneralActionsActionsCallbackInterfaces = new List<IGeneralActionsActions>();
    private readonly InputAction m_GeneralActions_Newaction;
    private readonly InputAction m_GeneralActions_ChangeTime;
    /// <summary>
    /// Provides access to input actions defined in input action map "GeneralActions".
    /// </summary>
    public struct GeneralActionsActions
    {
        private @GeneralGame m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GeneralActionsActions(@GeneralGame wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "GeneralActions/Newaction".
        /// </summary>
        public InputAction @Newaction => m_Wrapper.m_GeneralActions_Newaction;
        /// <summary>
        /// Provides access to the underlying input action "GeneralActions/ChangeTime".
        /// </summary>
        public InputAction @ChangeTime => m_Wrapper.m_GeneralActions_ChangeTime;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_GeneralActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GeneralActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GeneralActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GeneralActionsActions" />
        public void AddCallbacks(IGeneralActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_GeneralActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GeneralActionsActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
            @ChangeTime.started += instance.OnChangeTime;
            @ChangeTime.performed += instance.OnChangeTime;
            @ChangeTime.canceled += instance.OnChangeTime;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GeneralActionsActions" />
        private void UnregisterCallbacks(IGeneralActionsActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
            @ChangeTime.started -= instance.OnChangeTime;
            @ChangeTime.performed -= instance.OnChangeTime;
            @ChangeTime.canceled -= instance.OnChangeTime;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GeneralActionsActions.UnregisterCallbacks(IGeneralActionsActions)" />.
        /// </summary>
        /// <seealso cref="GeneralActionsActions.UnregisterCallbacks(IGeneralActionsActions)" />
        public void RemoveCallbacks(IGeneralActionsActions instance)
        {
            if (m_Wrapper.m_GeneralActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GeneralActionsActions.AddCallbacks(IGeneralActionsActions)" />
        /// <seealso cref="GeneralActionsActions.RemoveCallbacks(IGeneralActionsActions)" />
        /// <seealso cref="GeneralActionsActions.UnregisterCallbacks(IGeneralActionsActions)" />
        public void SetCallbacks(IGeneralActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_GeneralActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GeneralActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GeneralActionsActions" /> instance referencing this action map.
    /// </summary>
    public GeneralActionsActions @GeneralActions => new GeneralActionsActions(this);

    // UIIngame
    private readonly InputActionMap m_UIIngame;
    private List<IUIIngameActions> m_UIIngameActionsCallbackInterfaces = new List<IUIIngameActions>();
    private readonly InputAction m_UIIngame_OpenUIIngame;
    /// <summary>
    /// Provides access to input actions defined in input action map "UIIngame".
    /// </summary>
    public struct UIIngameActions
    {
        private @GeneralGame m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UIIngameActions(@GeneralGame wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UIIngame/OpenUIIngame".
        /// </summary>
        public InputAction @OpenUIIngame => m_Wrapper.m_UIIngame_OpenUIIngame;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UIIngame; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UIIngameActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UIIngameActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UIIngameActions" />
        public void AddCallbacks(IUIIngameActions instance)
        {
            if (instance == null || m_Wrapper.m_UIIngameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIIngameActionsCallbackInterfaces.Add(instance);
            @OpenUIIngame.started += instance.OnOpenUIIngame;
            @OpenUIIngame.performed += instance.OnOpenUIIngame;
            @OpenUIIngame.canceled += instance.OnOpenUIIngame;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UIIngameActions" />
        private void UnregisterCallbacks(IUIIngameActions instance)
        {
            @OpenUIIngame.started -= instance.OnOpenUIIngame;
            @OpenUIIngame.performed -= instance.OnOpenUIIngame;
            @OpenUIIngame.canceled -= instance.OnOpenUIIngame;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UIIngameActions.UnregisterCallbacks(IUIIngameActions)" />.
        /// </summary>
        /// <seealso cref="UIIngameActions.UnregisterCallbacks(IUIIngameActions)" />
        public void RemoveCallbacks(IUIIngameActions instance)
        {
            if (m_Wrapper.m_UIIngameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UIIngameActions.AddCallbacks(IUIIngameActions)" />
        /// <seealso cref="UIIngameActions.RemoveCallbacks(IUIIngameActions)" />
        /// <seealso cref="UIIngameActions.UnregisterCallbacks(IUIIngameActions)" />
        public void SetCallbacks(IUIIngameActions instance)
        {
            foreach (var item in m_Wrapper.m_UIIngameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIIngameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UIIngameActions" /> instance referencing this action map.
    /// </summary>
    public UIIngameActions @UIIngame => new UIIngameActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "GeneralActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GeneralActionsActions.AddCallbacks(IGeneralActionsActions)" />
    /// <seealso cref="GeneralActionsActions.RemoveCallbacks(IGeneralActionsActions)" />
    public interface IGeneralActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "New action" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNewaction(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ChangeTime" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChangeTime(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UIIngame" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UIIngameActions.AddCallbacks(IUIIngameActions)" />
    /// <seealso cref="UIIngameActions.RemoveCallbacks(IUIIngameActions)" />
    public interface IUIIngameActions
    {
        /// <summary>
        /// Method invoked when associated input action "OpenUIIngame" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpenUIIngame(InputAction.CallbackContext context);
    }
}
